/*
 * This file is generated by jOOQ.
 */
package com.umsign.blog.jooq.model;


import com.umsign.blog.jooq.model.tables.Author;
import com.umsign.blog.jooq.model.tables.Book;
import com.umsign.blog.jooq.model.tables.BookStore;
import com.umsign.blog.jooq.model.tables.BookToBookStore;
import com.umsign.blog.jooq.model.tables.JooqBoard;
import com.umsign.blog.jooq.model.tables.Language;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq extends SchemaImpl {

    private static final long serialVersionUID = -525836952;

    /**
     * The reference instance of <code>jooq</code>
     */
    public static final Jooq JOOQ = new Jooq();

    /**
     * The table <code>jooq.author</code>.
     */
    public final Author AUTHOR = com.umsign.blog.jooq.model.tables.Author.AUTHOR;

    /**
     * The table <code>jooq.book</code>.
     */
    public final Book BOOK = com.umsign.blog.jooq.model.tables.Book.BOOK;

    /**
     * The table <code>jooq.book_store</code>.
     */
    public final BookStore BOOK_STORE = com.umsign.blog.jooq.model.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>jooq.book_to_book_store</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = com.umsign.blog.jooq.model.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq.jooq_board</code>.
     */
    public final JooqBoard JOOQ_BOARD = com.umsign.blog.jooq.model.tables.JooqBoard.JOOQ_BOARD;

    /**
     * The table <code>jooq.language</code>.
     */
    public final Language LANGUAGE = com.umsign.blog.jooq.model.tables.Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private Jooq() {
        super("jooq", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            JooqBoard.JOOQ_BOARD,
            Language.LANGUAGE);
    }
}
