/*
 * This file is generated by jOOQ.
 */
package com.umsign.blog.jooq.model;


import com.umsign.blog.jooq.model.tables.Author;
import com.umsign.blog.jooq.model.tables.Book;
import com.umsign.blog.jooq.model.tables.BookStore;
import com.umsign.blog.jooq.model.tables.BookToBookStore;
import com.umsign.blog.jooq.model.tables.JooqBoard;
import com.umsign.blog.jooq.model.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.author</code>.
     */
    public static final Author AUTHOR = com.umsign.blog.jooq.model.tables.Author.AUTHOR;

    /**
     * The table <code>jooq.book</code>.
     */
    public static final Book BOOK = com.umsign.blog.jooq.model.tables.Book.BOOK;

    /**
     * The table <code>jooq.book_store</code>.
     */
    public static final BookStore BOOK_STORE = com.umsign.blog.jooq.model.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>jooq.book_to_book_store</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = com.umsign.blog.jooq.model.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>jooq.jooq_board</code>.
     */
    public static final JooqBoard JOOQ_BOARD = com.umsign.blog.jooq.model.tables.JooqBoard.JOOQ_BOARD;

    /**
     * The table <code>jooq.language</code>.
     */
    public static final Language LANGUAGE = com.umsign.blog.jooq.model.tables.Language.LANGUAGE;
}
