spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jooq?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  jooq:
    sql-dialect: mysql

logging:
  level:
    org.jooq.tools.LoggerListener: debug