/*
 * This file is generated by jOOQ.
 */
package com.umsign.blog.jooq.model.tables.records;


import com.umsign.blog.jooq.model.tables.JooqBoard;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqBoardRecord extends UpdatableRecordImpl<JooqBoardRecord> implements Record6<Integer, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1373254802;

    /**
     * Setter for <code>jooq.jooq_board.seq</code>.
     */
    public void setSeq(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq.jooq_board.seq</code>.
     */
    public Integer getSeq() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jooq.jooq_board.author</code>.
     */
    public void setAuthor(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq.jooq_board.author</code>.
     */
    public String getAuthor() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq.jooq_board.content</code>.
     */
    public void setContent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq.jooq_board.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq.jooq_board.read_cnt</code>.
     */
    public void setReadCnt(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jooq.jooq_board.read_cnt</code>.
     */
    public String getReadCnt() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jooq.jooq_board.add_date</code>.
     */
    public void setAddDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>jooq.jooq_board.add_date</code>.
     */
    public Timestamp getAddDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>jooq.jooq_board.mod_date</code>.
     */
    public void setModDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>jooq.jooq_board.mod_date</code>.
     */
    public Timestamp getModDate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JooqBoard.JOOQ_BOARD.SEQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return JooqBoard.JOOQ_BOARD.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return JooqBoard.JOOQ_BOARD.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JooqBoard.JOOQ_BOARD.READ_CNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return JooqBoard.JOOQ_BOARD.ADD_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return JooqBoard.JOOQ_BOARD.MOD_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSeq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getReadCnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getAddDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getModDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSeq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReadCnt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getAddDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getModDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JooqBoardRecord value1(Integer value) {
        setSeq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JooqBoardRecord value2(String value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JooqBoardRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JooqBoardRecord value4(String value) {
        setReadCnt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JooqBoardRecord value5(Timestamp value) {
        setAddDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JooqBoardRecord value6(Timestamp value) {
        setModDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JooqBoardRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JooqBoardRecord
     */
    public JooqBoardRecord() {
        super(JooqBoard.JOOQ_BOARD);
    }

    /**
     * Create a detached, initialised JooqBoardRecord
     */
    public JooqBoardRecord(Integer seq, String author, String content, String readCnt, Timestamp addDate, Timestamp modDate) {
        super(JooqBoard.JOOQ_BOARD);

        set(0, seq);
        set(1, author);
        set(2, content);
        set(3, readCnt);
        set(4, addDate);
        set(5, modDate);
    }
}
